const types = {
  // let declarations (lowercase)
  "*s": { type: "string", declaration: "let" },
  "*i": { type: "integer", declaration: "let" },
  "*f": { type: "float", declaration: "let" },
  "*b": { type: "boolean", declaration: "let" },
  "*c": { type: "character", declaration: "let" },
  "*a": { type: "array", declaration: "let" },
  "*d": { type: "dictionary", declaration: "let" },
  "*fn": { type: "function", declaration: "let" },
  "*v": { type: "void", declaration: "let" },
  "*any": { type: "any", declaration: "let" },
  "*p": { type: "pointer", declaration: "let" },
  "*o": { type: "object", declaration: "let" },
  "*t": { type: "tuple", declaration: "let" },
  "*e": { type: "enum", declaration: "let" },
  "*null": { type: "null", declaration: "let" },
  "*u": { type: "union", declaration: "let" },
  "*set": { type: "set", declaration: "let" },
  "*byte": { type: "byte", declaration: "let" },
  "*l": { type: "long", declaration: "let" },
  "*dbl": { type: "double", declaration: "let" },
  "*comp": { type: "complex", declaration: "let" },
  "*dt": { type: "datetime", declaration: "let" },
  "*file": { type: "file", declaration: "let" },
  "*stream": { type: "stream", declaration: "let" },
  "*opt": { type: "optional", declaration: "let" },
  "*range": { type: "range", declaration: "let" },
  "*err": { type: "error", declaration: "let" },
  "*regex": { type: "regex", declaration: "let" },
  "*uuid": { type: "uuid", declaration: "let" },
  "*json": { type: "json", declaration: "let" },

  // const declarations (uppercase)
  "*S": { type: "string", declaration: "const" },
  "*I": { type: "integer", declaration: "const" },
  "*F": { type: "float", declaration: "const" },
  "*B": { type: "boolean", declaration: "const" },
  "*C": { type: "character", declaration: "const" },
  "*A": { type: "array", declaration: "const" },
  "*D": { type: "dictionary", declaration: "const" },
  "*FN": { type: "function", declaration: "const" },
  "*V": { type: "void", declaration: "const" },
  "*ANY": { type: "any", declaration: "const" },
  "*P": { type: "pointer", declaration: "const" },
  "*O": { type: "object", declaration: "const" },
  "*T": { type: "tuple", declaration: "const" },
  "*E": { type: "enum", declaration: "const" },
  "*NULL": { type: "null", declaration: "const" },
  "*U": { type: "union", declaration: "const" },
  "*SET": { type: "set", declaration: "const" },
  "*BYTE": { type: "byte", declaration: "const" },
  "*L": { type: "long", declaration: "const" },
  "*DBL": { type: "double", declaration: "const" },
  "*COMP": { type: "complex", declaration: "const" },
  "*DT": { type: "datetime", declaration: "const" },
  "*FILE": { type: "file", declaration: "const" },
  "*STREAM": { type: "stream", declaration: "const" },
  "*OPT": { type: "optional", declaration: "const" },
  "*RANGE": { type: "range", declaration: "const" },
  "*ERR": { type: "error", declaration: "const" },
  "*REGEX": { type: "regex", declaration: "const" },
  "*UUID": { type: "uuid", declaration: "const" },
  "*JSON": { type: "json", declaration: "const" },
};

export default types; // Export the types object for use in other modules
